# Schema for the configuration files of the Route Play module.
route_play.settings:
  type: config_object
  label: 'Route Play settings'
  mapping:
    salutation:
      type: string
      label: 'Salutation'
