<?php

/**
 * Implements hook_preprocess_pager().
 */
function ajax_pager_table_preprocess_pager(&$variables): void {
  // Check if the pager items exist
  if (isset($variables['items'])) {
    // Loop through each pager item
    foreach ($variables['items']['pages'] as &$page) {
      // Set the URL to use my custom AJAX route.
      if (!str_contains($page['href'], '_wrapper_format=drupal_ajax')) {
        // Retrieve the current page number
        $equalsPosition = strpos($page['href'], '=') + 1;
        $pageNumber = (int) substr($page['href'], $equalsPosition);
        // Update the URL to use the custom route with the current page number
        $url = Drupal\Core\Url::fromRoute('ajax_pager.refresh_table', ['page' => $pageNumber]);
        $url_text = $url->toString();
        $page['href'] = $url_text;

//        // Try using the '#ajax' property.
//        // Add '#ajax' property to the pager item
//        $page['#ajax'] = [
//          'callback' => '\Drupal\ajax_pager_table\Controller\AjaxPagerTableController::refreshAjaxBlock',
//          'wrapper' => 'ajax-pager-wrapper' . $pageNumber,
//          'url' => $url,
//          'options' => ['query' => ['_wrapper_format' => 'drupal_ajax']],
//        ];
      }
      // Add 'use-ajax' class to each pager link
      $page['attributes']->addClass('use-ajax');
    }
  }
}
