lb_plus.settings:
  type: config_object
  label: 'Layout Builder + settings'
  mapping:
    colors:
      type: sequence
      label: 'Colors'
      sequence:
        type: string
        label: 'Color'
